### ISSUE TITLE
Sorry， I mean deblur

### ISSUE THREAD

**Issue by shede1988** [cgtuebingen/learning-blind-motion-deblurring#11]
How to use this project to deblur?

**Comment by shede1988** [comment]
How to use this project to deblur  a picture?

**Comment by PatWie** [comment]
Please do not open *different* issues for the *same* question.
If you need a help feel free to drop me an email.
But *please* do not distribute your questions on multiple issues within a few day.

**Comment by shede1988** [comment]
I am so sorry! I really don't know how to test! I mean how to deblur a picture! This project seem to just train and learning,but it can't test to deblur a picture?
