### ISSUE TITLE
I am so sorry! I really don't know how to test! I mean how to deblur a picture! This project seem to just train and learning,but it can't test to deblur a picture?

### ISSUE THREAD

**Issue by shede1988** [cgtuebingen/learning-blind-motion-deblurring#12]
I am so sorry! I really don't know how to test! I mean how to deblur a picture! This project seem to just train and learning,but it can't test to deblur a picture?

**Comment by PatWie** [comment]
I cannot provide a simple inference code part, as the TensorFlow graph depends on the input length (not the model itself). SO the inference part depends on your specific usecase.

Doing inference with Tensorpack is straight-forward, just specify
```python
SEQ_LEN = .... 

pred = PredictConfig(
        session_init=get_model_loader(model_path),
        model=Model(),
        input_names=['blurry'],
        output_names=['estimate_t%i_l0' % k for k in range(....)])

    # prepare output
    pred = OfflinePredictor(pred)
    sharp_image = pred([your_image_as_numpy_array])[-1][0, ...]
```

Again, please re-open your other issues with the same question, if required.
