### ISSUE TITLE
fatal error: opencv2/core.hpp: No such file or directory

### ISSUE THREAD

**Issue by jackytu256** [cgtuebingen/learning-blind-motion-deblurring#2]
Hi,

 I was trying to do "make all" and then I got this error "fatal error: opencv2/core.hpp: No such file or directory". How can I fix it ?

My working environment is as below

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

opencv version: 2.4.8
```

Thanks

**Comment by PatWie** [comment]
You need to add OpenCV to your include path (`OpenCV_DIR`). My `.zshrc` contains

```
export OpenCV_DIR=${OPT_PATH}/opencv-3.1.0/share/OpenCV
export LD_LIBRARY_PATH=${OPT_PATH}/opencv-3.1.0/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${OPT_PATH}/opencv-3.1.0/lib/pkgconfig
```

I use version 3.1 compile from source.
