### ISSUE TITLE
can find cudaoptflow.hpp

### ISSUE THREAD

**Issue by shede1988** [cgtuebingen/learning-blind-motion-deblurring#3]
can find cudaoptflow.hpp

**Comment by shede1988** [comment]
I use opencv2.4.13

**Comment by PatWie** [comment]
See
https://github.com/cgtuebingen/learning-blind-motion-deblurring/issues/2

**Comment by shede1988** [comment]
can not find cudaoptflow.hpp

**Comment by PatWie** [comment]
The linked issue gives a solution: you need the correct OpenCV version and adjust the path to let the compiler find the header files.
