### ISSUE TITLE
Failed to load OpenCL runtime (expected version 1.1+)

### ISSUE THREAD

**Issue by shede1988** [cgtuebingen/learning-blind-motion-deblurring#7]
Failed to load OpenCL runtime (expected version 1.1+)

**Comment by PatWie** [comment]
This is not an issue (it is a hack):

https://github.com/ppwwyyxx/tensorpack/blob/04d6055915bed93fbd9239986931cd1853995204/tensorpack/libinfo.py#L5

**Comment by shede1988** [comment]
Does that mean I don't have OpenCL installed?
So do I have to install OpenCL?

**Comment by PatWie** [comment]
read carefully:
https://github.com/ppwwyyxx/tensorpack/blob/04d6055915bed93fbd9239986931cd1853995204/tensorpack/libinfo.py#L4
