### ISSUE TITLE
This project is only about training, but how do I use this project to blur the picture?

### ISSUE THREAD

**Issue by shede1988** [cgtuebingen/learning-blind-motion-deblurring#9]
This project is only about training, but how do I use this project to blur the picture?

**Comment by shede1988** [comment]
for i in `seq 1 30`; do
    python data_sampler.py --pattern '/home/alan/train/*_blurry.mp4' --lmdb /home/alan/train$i.lmdb --num 5000
done
for i in `seq 1 10`; do
    python data_sampler.py --pattern '/home/alan/train/*_blurry.mp4' --lmdb /home/alan/train/val$i.lmdb --num 5000
done

**Comment by shede1988** [comment]
but I don't have train$i.lmdb and val$i.lmdb，what should I do?

**Comment by PatWie** [comment]
Please read the code carefully. There are two places for blurring images:
[motion blur](https://github.com/cgtuebingen/learning-blind-motion-deblurring/blob/master/synthblur/src/blur.cpp) and [camera shake](https://github.com/cgtuebingen/learning-blind-motion-deblurring/blob/master/psf.py)

**Comment by shede1988** [comment]
Sorry， I mean deblur

**Comment by PatWie** [comment]
I re-trained a slightly larger model in TensorPack just for testing the TensorPack library some months ago. It seems to have similar performance (although it is not compatible with this GitHub project).
Find the inference code/weights here:
http://files.patwie.com/suppmat/patwie_iccv17_deblurring_model.tar.gz
